Homework 1. Task 2. Dubrovchenko Mark
Mmorgenn/spbu_second_course_python pull request #2
Opened 2024-03-25 18:32 UTC by Mmorgenn

2024-04-27 16:35 UTC, SpirinEgor requested changes
Кажется если сделать `split` и `merge` частью `Node`, то сам класс `Treap` значительно упроститься -- не будет статических методов, пустышек при создании и тп

2024-04-27 16:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +        self.right: Node | None = None
А это валидное типизирование? Точно ли корректная альтернатива `Optional[Node]`

2024-04-27 16:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +        return f"Node(value={self.value}, key={self.key}, priority={self.priority}, left={self.left}, right={self.right}, size={self.size})"
Как будто бы строковое представление должно быть одинаковое для одинаковых вершин. А из-за печати левого и правого поддерева они будут отличаться

2024-04-27 16:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +        tree_additional.root = node_additional
Выглядит странно -- какие-то промежуточные объекты создаются, что-то куда-то записывается...

2024-04-27 16:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +                return recursion_find(node.right)
Кажется небольшое дублирование кода

2024-04-27 16:49 UTC, Mmorgenn commented on src/Homework/Homework_1/treap.py
> +        self.right: Node | None = None
https://docs.python.org/3/library/typing.html#typing.Optional

2024-05-20 15:35 UTC, SpirinEgor requested changes

2024-05-20 15:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +    def __init__(self, root: Node | None = None) -> None:
Почему сюда вообще какая-то вершина может передаваться? Внутри нее нет никакого поддержания инварианта -- подсунуть могут все что угодно

2024-05-20 15:35 UTC, SpirinEgor commented on src/Homework/Homework_1/treap.py
> +            raise KeyError("There is no such key")
Ну тут тогда уместнее не KeyError (ты уже проверил, что такая вершина есть), а что-то вроде RuntimeError

2024-05-25 15:32 UTC, SpirinEgor approved these changes

2024-05-25 15:32 UTC, merged