Homework 3. Task 1. Dubrovchenko Mark
Mmorgenn/spbu_second_course_python pull request #5
Opened 2024-04-29 01:11 UTC by Mmorgenn

2024-05-20 15:44 UTC, SpirinEgor requested changes

2024-05-20 15:44 UTC, SpirinEgor commented on src/Homework/Homework_3/main_weather.py
> +API_KEY = "69122dc7f1c80846ab51a95cab1062de"
А вот так никогда нельзя, такие секреты надо хранить в закрытом месте.
Как правило, это чтение переменной окружения, а в CI оно туда попадает из Secrets (можно настроить для Action)

2024-05-20 15:44 UTC, SpirinEgor commented on src/Homework/Homework_3/orm.py
> +            setattr(cls, name, ORMDescriptor(name))
А это не часть orm meta? То есть не правильнее ли подсовывать нужные поля в мете, а тут проверять, что нужная мета у класса?

2024-05-20 15:44 UTC, SpirinEgor commented on src/Homework/Homework_3/main_weather.py
> +class Weather(ORM, metaclass=ORMMeta):
А можем ли упростить, чтобы достаточно было только мету указать? Двойное указание кажется излишним...

2024-05-20 15:50 UTC, Mmorgenn commented on src/Homework/Homework_3/main_weather.py
> +API_KEY = "69122dc7f1c80846ab51a95cab1062de"
Ну там все равно с левой почти ключ)

2024-05-27 15:58 UTC, SpirinEgor requested changes

2024-05-27 15:58 UTC, SpirinEgor commented on src/Homework/Homework_3/main_weather.py
> +class Personal_Weather(metaclass=ORMMeta):
Какой-то странный нейминг, зачем тут подчеркивание?)

2024-05-27 15:58 UTC, SpirinEgor commented on src/Homework/Homework_3/orm.py
> +        self.value = None
На парах обсуждали, чем плохо хранить значение внутри дескриптора. Здесь к тому же все сломается, если будет несколько инстансов датакласса.

2024-05-27 15:58 UTC, SpirinEgor commented on src/Homework/Homework_3/orm.py
> +            if type(field_type) is ORMMeta:
Для этого есть `isintance`

2024-05-27 15:58 UTC, SpirinEgor commented on src/Homework/Homework_3/orm.py
> +            self.value = new_value
А если у нас вложенные датаклассы и тут надо перенаправить словарь в следующий ORM объект? Сейчас кажется мы просто словарь переприсвоим и все сломается...

2024-05-27 15:58 UTC, SpirinEgor commented on tests/Homework/Homework_3/test_orm.py
> +    info: Person
Нужен тест, что после создания Worker из словаря, а потом обращения к .info его тип останется Person

2024-05-30 11:58 UTC, SpirinEgor approved these changes

2024-05-30 11:58 UTC, merged